Repository openacid/celeritasdb, pull requests merged in 2020-03, with the labels that each got.

#162 feat: Instance::conflict() to check if two instance contains conflicting commands
  components/epaxos/src/qpaxos/mod.rs
  components/epaxos/src/qpaxos/t.rs
  components/epaxos/src/qpaxos/test_instance.rs
  components/epaxos/src/snapshot/iters.rs
  components/epaxos/src/snapshot/mem_engine/memdb.rs
  components/epaxos/src/snapshot/test_engine.rs
Labels: PR: reviewed-approved

#163 fix: InstanceIter
  components/epaxos/src/snapshot/iters.rs
  components/epaxos/src/snapshot/mem_engine/memdb.rs
  components/epaxos/src/snapshot/traits.rs
Labels: PR: reviewed-approved

#164 feat: impl handle-commit-request
  components/epaxos/build.rs
  components/epaxos/src/protos/errors.proto
  components/epaxos/src/protos/message.proto
  components/epaxos/src/qpaxos/mod.rs
  components/epaxos/src/qpaxos/t.rs
  components/epaxos/src/replica/replica.rs
Labels: PR: unreviewed

#166 feat: add test to handle_commit_request
  components/epaxos/src/replica/mod.rs
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_replica.rs
  components/epaxos/src/replica/tests/replica_tests.rs
Labels: PR: reviewed-approved

#168 调整 snapshot traits 的测试结构
  components/epaxos/src/snapshot/mem_engine/memdb.rs
  components/epaxos/src/snapshot/mod.rs
  components/epaxos/src/snapshot/traits/mod.rs
  components/epaxos/src/snapshot/traits/test_base.rs
  components/epaxos/src/snapshot/traits/traits.rs
Labels: PR: reviewed-approved

#169 feat: add error InvalidRequest; convert Error for transport
  components/epaxos/src/protos/errors.proto
  components/epaxos/src/qpaxos/t.rs
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/snapshot/errors.rs
Labels: PR: unreviewed

#167 rocks_engine impl snapshot.Base
  components/epaxos/src/snapshot/rocks_engine/engine.rs
  components/epaxos/src/snapshot/rocks_engine/mod.rs
  components/epaxos/src/snapshot/rocks_engine/test_engine.rs
Labels: PR: unreviewed

#177 test: add test of handle_accept_request
  components/epaxos/src/replica/test_replica.rs
Labels: PR: reviewed-approved

#178 refactor: replica: use macro to simplify invalid request test
  components/epaxos/src/replica/test_replica.rs
Labels: PR: reviewed-approved

#180 refactery: move mem_engine/tests to traits/test_base
  components/epaxos/src/snapshot/mem_engine/memdb.rs
  components/epaxos/src/snapshot/rocks_engine/test_engine.rs
  components/epaxos/src/snapshot/traits/test_base.rs
Labels: PR: reviewed-approved

#185 feat: add InstanceIdVec as wrapper of Vec<InstanceId>
  components/epaxos/src/protos/instance.proto
  components/epaxos/src/qpaxos/mod.rs
  components/epaxos/src/qpaxos/test_instance.rs
Labels: PR: reviewed-approved

#184 instance and base iter support reverse mod
  components/epaxos/src/snapshot/iters.rs
  components/epaxos/src/snapshot/mem_engine/memdb.rs
  components/epaxos/src/snapshot/rocks_engine/engine.rs
  components/epaxos/src/snapshot/test_engine.rs
  components/epaxos/src/snapshot/traits/traits.rs
Labels: PR: unreviewed

#186 feat: InstanceIdVec: add a lot From<...> impl
  components/epaxos/build.rs
  components/epaxos/src/qpaxos/mod.rs
  components/epaxos/src/qpaxos/test_instance.rs
Labels: PR: unreviewed

#191 feat: add macro to simplify making Command and InstanceId
  components/epaxos/build.rs
  components/epaxos/src/qpaxos/macros.rs
  components/epaxos/src/qpaxos/mod.rs
  components/epaxos/src/qpaxos/test_command.rs
  components/epaxos/src/qpaxos/test_instance.rs
Labels: PR: reviewed-approved

#193 feat: add macro `inst!` to easily create an instance
  components/epaxos/src/lib.rs
  components/epaxos/src/qpaxos/macros.rs
  components/epaxos/src/qpaxos/mod.rs
  components/epaxos/src/qpaxos/test_instance.rs
  components/epaxos/src/replica/test_replica.rs
Labels: PR: unreviewed

#196 test: add test of None fields for handle-fast-accept-request
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_replica.rs
Labels: PR: reviewed-approved

#189 feat: handle accept reply
  components/epaxos/src/protos/instance.proto
  components/epaxos/src/replica/mod.rs
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/status.rs
  components/epaxos/src/replica/test_replica.rs
  components/epaxos/src/replica/tests/exec_tests.rs
Labels: PR: unreviewed

#197 refactor: use macro to simplify instance creation for test
  components/epaxos/src/qpaxos/macros.rs
  components/epaxos/src/qpaxos/test_instance.rs
  components/epaxos/src/replica/test_replica.rs
Labels: PR: unreviewed

#198 refactor: use Arc<Mutex<BTreeMap>> to impl mem-engine
  components/epaxos/src/snapshot/mem_engine/memdb.rs
  components/epaxos/src/snapshot/mem_engine/mod.rs
Labels: PR: unreviewed

#199 Macor init inst
  .travis.yml
  components/epaxos/Cargo.toml
  components/epaxos/src/qpaxos/macros.rs
  components/epaxos/src/qpaxos/mod.rs
  components/epaxos/src/qpaxos/test_macros.rs
Labels: PR: unreviewed

#200 replica::new_instance
  components/epaxos/src/replica/exec.rs
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_exec.rs
  components/epaxos/src/replica/test_replica.rs
  components/epaxos/src/snapshot/mem_engine/memdb.rs
  components/epaxos/src/snapshot/rocks_engine/engine.rs
  components/epaxos/src/snapshot/traits/traits.rs
Labels: PR: reviewed-approved

#201 fix: quorum() gives wrong result when n=2k
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_replica.rs
Labels: PR: reviewed-approved

#205 feat: status: add get_fast_commit_dep() to find out what dep can be s…
  components/epaxos/build.rs
  components/epaxos/src/lib.rs
  components/epaxos/src/replica/mod.rs
  components/epaxos/src/replica/status.rs
  components/epaxos/src/replica/test_status.rs
Labels: PR: reviewed-approved

#208 feat: add qpaxos::errors
  .travis.yml
  components/epaxos/src/qpaxos/errors.rs
  components/epaxos/src/qpaxos/mod.rs
  components/epaxos/src/qpaxos/test_errors.rs
Labels: PR: partially-approved

#204 feat: bcast request to other replica
  components/epaxos/src/replica/mod.rs
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_exec.rs
  components/epaxos/src/replica/test_replica.rs
  components/epaxos/src/replica/test_util.rs
Labels: PR: unreviewed

#211 refactor: use one Status to track all phases: fast, accept, prepare etc.
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/status.rs
  components/epaxos/src/replica/test_replica.rs
Labels: PR: unreviewed

#213 feat: mod replication impl replication algo.
  components/epaxos/build.rs
  components/epaxos/src/lib.rs
  components/epaxos/src/qpaxos/errors.rs
  components/epaxos/src/replica/errors.rs
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/status.rs
  components/epaxos/src/replication/errors.rs
  components/epaxos/src/replication/hdlreply.rs
  components/epaxos/src/replication/mod.rs
  components/epaxos/src/replication/test_hdlreply.rs
  components/epaxos/src/snapshot/errors.rs
Labels: PR: reviewed-approved

#216 test: add test of Status::new()
  components/epaxos/src/replica/status.rs
  components/epaxos/src/replica/test_replica.rs
  components/epaxos/src/replica/test_status.rs
  components/epaxos/src/replication/test_hdlreply.rs
Labels: PR: unreviewed
