Repository openacid/celeritasdb, pull requests merged in 2020-04, with the labels that each got.

#217 refactor: conf: make node id.
  components/epaxos/src/conf/conf.rs
  components/epaxos/src/conf/errors.rs
  components/epaxos/src/conf/tests/conf_tests.rs
Labels: PR: unreviewed

#218 feat: Cluster add replica-to-node-id mapping.
  components/epaxos/src/conf/conf.rs
  components/epaxos/src/conf/errors.rs
  components/epaxos/src/conf/tests/conf_tests.rs
Labels: PR: unreviewed

#219 feat: use stucture in `groups->replica->node` structure to define a c…
  components/epaxos/src/conf/conf.rs
  components/epaxos/src/conf/errors.rs
  components/epaxos/src/conf/tests/conf_tests.rs
Labels: PR: partially-approved

#221 feat: use ClusterInfo to config the server
  Cargo.toml
  src/bin/cele.rs
  tests/support/mod.rs
Labels: PR: partially-approved

#222 refactor: add cluster into Server
  components/epaxos/src/conf/conf.rs
  src/bin/cele.rs
Labels: PR: partially-approved

#223 feat: ClusterInfo need to track key-range to group mapping
  components/epaxos/src/conf/conf.rs
  components/epaxos/src/conf/errors.rs
  components/epaxos/src/conf/tests/conf_tests.rs
  tests/support/mod.rs
Labels: PR: unreviewed

#225 feat: replica: add get_max_instance_ids(), which would be used when i…
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_replica.rs
Labels: PR: partially-approved

#226 change: Status now has an instance in it instead of a reference
  components/epaxos/src/replica/status.rs
  components/epaxos/src/replica/test_status.rs
  components/epaxos/src/replication/hdlreply.rs
  components/epaxos/src/replication/test_hdlreply.rs
Labels: PR: reviewed-approved

#227 fix: if fast-quorum is 0, then n==1. then fast-commit can always be done
  components/epaxos/src/replica/status.rs
  components/epaxos/src/replica/test_status.rs
Labels: PR: partially-approved

#228 feat: Status.get_accept_deps(): to get deps for accept-request
  components/epaxos/src/replica/status.rs
  components/epaxos/src/replica/test_status.rs
Labels: PR: partially-approved

#229 fix: bug of fast-quorum: it must be greater than quorum
  components/epaxos/src/qpaxos/quorums.rs
  components/epaxos/src/qpaxos/test_quorums.rs
  components/epaxos/src/replica/test_replica.rs
Labels: PR: partially-approved

#230 Get fast commit deps
  components/epaxos/src/replica/status.rs
  components/epaxos/src/replica/test_status.rs
Labels: PR: partially-approved

#233 remove transaction trait, add write batch and deletels, refine some m…
  components/epaxos/src/replica/exec.rs
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_exec.rs
  components/epaxos/src/snapshot/errors.rs
  components/epaxos/src/snapshot/iters.rs
  components/epaxos/src/snapshot/mem_engine/memdb.rs
  components/epaxos/src/snapshot/rocks_engine/engine.rs
  components/epaxos/src/snapshot/rocks_engine/mod.rs
  components/epaxos/src/snapshot/rocks_engine/rocks.rs
  components/epaxos/src/snapshot/test_engine.rs
  components/epaxos/src/snapshot/traits/traits.rs
Labels: PR: unreviewed

#236 mem and rocks use same public trait, kv/instance/ref use diff cf
  components/epaxos/src/replica/exec.rs
  components/epaxos/src/replica/test_replica.rs
  components/epaxos/src/snapshot/iters.rs
  components/epaxos/src/snapshot/mem_engine/memdb.rs
  components/epaxos/src/snapshot/mem_engine/mod.rs
  components/epaxos/src/snapshot/rocks_engine/engine.rs
  components/epaxos/src/snapshot/rocks_engine/mod.rs
  components/epaxos/src/snapshot/rocks_engine/test_engine.rs
  components/epaxos/src/snapshot/test_engine.rs
  components/epaxos/src/snapshot/traits/traits.rs
Labels: PR: unreviewed

#239 exec replace transaction with write batch
  Cargo.toml
  components/epaxos/Cargo.toml
  components/epaxos/build.rs
  components/epaxos/src/protos/command.proto
  components/epaxos/src/replica/exec.rs
  components/epaxos/src/replica/test_exec.rs
  components/epaxos/src/snapshot/errors.rs
  components/epaxos/src/snapshot/mem_engine/memdb.rs
  components/epaxos/src/snapshot/rocks_engine/engine.rs
  components/epaxos/src/snapshot/traits/traits.rs
Labels: PR: unreviewed

#240 fix: finish new replica func
  components/epaxos/src/conf/conf.rs
  components/epaxos/src/replica/errors.rs
  components/epaxos/src/replica/exec.rs
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_replica.rs
  components/epaxos/src/replica/test_util.rs
  components/epaxos/src/serverdata/serverdata.rs
  components/epaxos/src/snapshot/rocks_engine/engine.rs
Labels: PR: unreviewed

#243 refactor: move redis api impl into standalone file
  src/bin/cele.rs
  src/lib.rs
  src/redisapi/mod.rs
  src/redisapi/redisapi.rs
Labels: PR: reviewed-approved

#244 feat: Server: add stop(), join() and impl Drop
  src/bin/cele.rs
  src/redisapi/redisapi.rs
Labels: PR: unreviewed

#242 refactor: create a storage crate for snapshot
  Cargo.toml
  components/epaxos/Cargo.toml
  components/epaxos/src/conf/conf.rs
  components/epaxos/src/conf/mod.rs
  components/epaxos/src/iters/iters.rs
  components/epaxos/src/iters/mod.rs
  components/epaxos/src/iters/test_iters.rs
  components/epaxos/src/lib.rs
  components/epaxos/src/qpaxos/mod.rs
  components/epaxos/src/replica/errors.rs
  components/epaxos/src/replica/exec.rs
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_exec.rs
  components/epaxos/src/replica/test_replica.rs
  components/epaxos/src/replica/test_status.rs
  components/epaxos/src/replica/test_util.rs
  components/epaxos/src/replication/errors.rs
  components/epaxos/src/replication/test_hdlreply.rs
  components/epaxos/src/serverdata/serverdata.rs
  components/epaxos/src/serverdata/test_serverdata.rs
  components/epaxos/src/snapshot/enum_str.rs
  components/epaxos/src/snapshot/iters.rs
  components/epaxos/src/snapshot/rocks_engine/test_engine.rs
  components/epaxos/src/snapshot/test_engine.rs
  components/epaxos/src/snapshot/traits/mod.rs
  components/epaxos/src/snapshot/traits/traits.rs
  components/epaxos/src/tokey.rs
  components/storage/Cargo.toml
  components/storage/src/errors.rs
  components/storage/src/lib.rs
  components/storage/src/mem_engine/memdb.rs
  components/storage/src/mem_engine/mod.rs
  components/storage/src/rocks_engine/engine.rs
  components/storage/src/rocks_engine/mod.rs
  components/storage/src/rocks_engine/rocks.rs
  components/storage/src/test_engine.rs
  components/storage/src/traits.rs
  src/bin/cele.rs
  src/server/server.rs
  tests/support/mod.rs
Labels: PR: unreviewed

#246 refactor: new_instance() should store the created instance in storage.
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_replica.rs
Labels: PR: unreviewed

#248 Fix status
  components/epaxos/src/replica/status.rs
  components/epaxos/src/replica/test_status.rs
  components/epaxos/src/replication/hdlreply.rs
  components/epaxos/src/replication/test_hdlreply.rs
Labels: PR: partially-approved

#250 feat: replication impl for a cluster of 1 member
  components/epaxos/src/lib.rs
  components/epaxos/src/replica/test_replica.rs
  components/epaxos/src/replication/errors.rs
  components/epaxos/src/replication/mod.rs
  components/epaxos/src/replication/replication.rs
  src/redisapi/redisapi.rs
  tests/test_setget.rs
Labels: PR: partially-approved

#251 refactor: move code: bcast_xxx moved to epaxos/replication/ test util…
  components/epaxos/src/lib.rs
  components/epaxos/src/replica/mod.rs
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_exec.rs
  components/epaxos/src/replica/test_replica.rs
  components/epaxos/src/replica/test_util.rs
  components/epaxos/src/replication/broadcast.rs
  components/epaxos/src/replication/mod.rs
  components/epaxos/src/replication/replication.rs
  components/epaxos/src/replication/test_broadcast.rs
  components/epaxos/src/replication/test_hdlreply.rs
  components/epaxos/src/testutil.rs
  src/server/server.rs
Labels: PR: partially-approved

#253 feat: impl Display for qpaxos data types
  components/epaxos/src/qpaxos/display.rs
  components/epaxos/src/qpaxos/mod.rs
  components/epaxos/src/qpaxos/test_display.rs
Labels: PR: partially-approved

#256 feat: add start replica exec thread
  Cargo.toml
  components/epaxos/Cargo.toml
  components/epaxos/src/qpaxos/macros.rs
  src/server/server.rs
  tests/test_replica.rs
Labels: PR: unreviewed

#257 refactor:
  components/epaxos/build.rs
  components/epaxos/src/protos/instance.proto
  components/epaxos/src/protos/message.proto
  components/epaxos/src/protos/qpaxos.proto
  components/epaxos/src/qpaxos/display.rs
  components/epaxos/src/qpaxos/macros.rs
  components/epaxos/src/qpaxos/mod.rs
  components/epaxos/src/qpaxos/t.rs
  components/epaxos/src/qpaxos/test_display.rs
  components/epaxos/src/qpaxos/test_instance.rs
  components/epaxos/src/qpaxos/test_macros.rs
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_replica.rs
  components/epaxos/src/replication/broadcast.rs
  components/epaxos/src/replication/hdlreply.rs
  components/epaxos/src/replication/replication.rs
  components/epaxos/src/replication/test_broadcast.rs
  components/epaxos/src/replication/test_hdlreply.rs
  components/epaxos/src/service/service.rs
  components/epaxos/tests/test_repl_server.rs
  tests/test_replica.rs
  tests/test_setget.rs
Labels: PR: partially-approved

#259 feat: add storage with namespace support
  components/storage/src/lib.rs
  components/storage/src/test_namespace.rs
  components/storage/src/test_traits.rs
  components/storage/src/traits.rs
Labels: PR: reviewed-approved

#261 Display replicate request reply
  components/epaxos/src/qpaxos/display.rs
  components/epaxos/src/qpaxos/test_display.rs
Labels: PR: reviewed-approved

#266 feat: replica exec send reply to client
  components/epaxos/src/replica/exec.rs
  components/epaxos/src/replica/replica.rs
  components/epaxos/src/replica/test_exec.rs
  components/epaxos/src/testutil.rs
  src/server/server.rs
Labels: PR: unreviewed

#267 feat: removes ref:max from storage. A replica does not need to track max-instance-id to work well.
  components/epaxos/src/replica/exec.rs
  components/epaxos/src/replica/test_exec.rs
  components/storage/src/test_engine.rs
  components/storage/src/traits.rs
  tests/test_replica.rs
Labels: PR: unreviewed

#268 feat: add a global logger
  Cargo.toml
  components/epaxos/Cargo.toml
  components/epaxos/src/lib.rs
  components/epaxos/src/replica/exec.rs
  src/bin/cele.rs
  src/lib.rs
  src/redisapi/redisapi.rs
  src/server/server.rs
  src/setup/mod.rs
  src/setup/setup.rs
Labels: PR: unreviewed
